from .auth_routes import auth_bp
from .user_routes import user_bp
from .admin_routes import admin_bp
from .movie_routes import movie_bp
from .series_routes import series_bp
from .payment_routes import payment_bp
from .analytics_routes import analytics_bp
from .review_routes import review_bp
from .download_routes import download_bp
